name: Flutter CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "2.2.3"

      - name: Install dependencies
        run: flutter pub get

      - name: Run tests
        env:
          FIREBASE_API_KEY: AIzaSyAalllSqkskiXs4PWBnUTVSjKauLsXdfH8
            FIREBASE_APP_ID: 1:489990357572:android:42b5fee178949b2d7c7211
            FIREBASE_MESSAGING_SENDER_ID: 489990357572
            FIREBASE_PROJECT_ID: peuty-3030d
        run: flutter test --coverage

      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: coverage/lcov.info
